### ISSUE TITLE
Feature: add token count for function call

### ISSUE THREAD

**Issue by ChuxiJ** [KillianLucas/tokentrim#8]
**Subject:** Inconsistencies and Limitations in Function Description Handling

**Body:**

I've observed several issues related to how OpenAI handles function descriptions, particularly when they are part of a thread. Here are the specifics:

1. **Function Descriptions in Threads:** OpenAI seems to insert function descriptions as the second message in a thread, typically as a system message. This behavior might need clarification or documentation.

2. **Exposure of Elements to the Model:** It appears that examples, titles, and most validations are not directly exposed to the model. However, default values and required fields are visible to it. This distinction might impact the model's understanding or responses.

3. **Description De-indentation:** OpenAI tends to de-indent the descriptions it includes. While this might be a formatting choice, understanding the rationale or having control over this behavior could be beneficial.

4. **Handling of Nested Objects:** While nested objects are allowed, the descriptions within these nested objects are not exposed to the model. This could lead to a loss of context or clarity when dealing with complex structures.

5. **Inconsistencies with Object Types and Optional Fields:** There seems to be inconsistent handling of object types with unspecified keys and optional fields. I have documented specific instances and patterns in the attached notebook.

I've attached a notebook to this issue that illustrates these points with examples. Any clarification, documentation updates, or consideration for future improvements would be greatly appreciated.

reference: 

1. https://gist.github.com/CGamesPlay/dd4f108f27e2eec145eedf5c717318f5
2. https://community.openai.com/t/how-to-calculate-the-tokens-when-using-function-call/266573/24

**Comment by ericrallen** [comment]
Hey there, @ChuxiJ!

This is super interesting.

I've noticed some discrepancies but haven't had a chance to dig into how functions are handled on the OpenAI side when it comes to tokenization.

I need to dig into this a little more before I feel qualified to look at the PR, but thanks so much for tackling this and providing the references so we can catch up on the context around the issue.
